name:                balcony
version:             0.1.0.0
github:              "borkdude/balcony"
license:             BSD3
author:              "Michiel Borkent"
maintainer:          "michielborkent@gmail.com"
copyright:           "2018 Michiel Borkent"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/borkdude/balcony#readme>

dependencies:
- base >= 4.7 && < 5
- postgresql-simple
- aeson
- bytestring
- wreq
- lens
- time
- scientific
- HaskellNet
- HaskellNet-SSL
- mime-mail
- text
- formatting

library:
  source-dirs: src

executables:
  balcony-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - balcony

tests:
  balcony-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - balcony
